// List of streets in Fitchburg, MA
export const FITCHBURG_STREETS: string[] = [
  'Abbott Ave',
  'Abbott Ave Ext',
  'Abbott St',
  'Abbott St Ext',
  'Abbott St Passway',
  'Academy St',
  'Adams St',
  'Airport Rd',
  'Albee St',
  'Alden St',
  'Alice Ave',
  'Allen Pl',
  'Allen St',
  'Allen St Passway',
  'Allen St Rear',
  'Allston Pl',
  'Almont Ave',
  'Almont Ter',
  'Alpine Rd',
  'Alpine Ter',
  'Amiott St',
  'Anastasia Way',
  'Andover St',
  'Andrews St',
  'Angela Way',
  'Anita Dr',
  'Apple Tree Hill',
  'Appleton Cir',
  'Arbor Way',
  'Arcadia Ave',
  'Arch Pl',
  'Arden Mills Way',
  'Arden St',
  'Arlington St',
  'Armand Ave',
  'Arn How Farm Rd',
  'Arthur St',
  'Ash St',
  'Ashburnham Hill Rd',
  'Ashburnham St',
  'Ashby State Rd',
  'Ashby West Rd',
  'Athol St',
  'Athol St Ext',
  'Atkins St',
  'Atlantic Ave',
  'Authority Dr',
  'Autumn Dr',
  'Avon Pl',
  'Azalea St',
  'Bacon St',
  'Bagley Ave',
  'Bailey St',
  'Baker St',
  'Balch St',
  'Baltic Ln',
  'Bamford Ave',
  'Bancroft St',
  'Bank Row',
  'Barbadoro Ln',
  'Barnes Ave',
  'Barrows St',
  'Bartlett St',
  'Bartlett St Ext',
  'Bartlett St Passway',
  'Bascom Pl',
  'Bassett St',
  'Bates St',
  'Baton Ave',
  'Battles St',
  'Bayberry Hill Rd',
  'Beach St',
  'Beacon St',
  'Beech St',
  'Beechmont St',
  'Beekman St',
  'Bel Air Dr',
  'Bella Vista Ave',
  'Belli Ave',
  'Belmont Ave',
  'Belmont St',
  'Bemis Rd',
  'Bennett Rd',
  'Benoit St',
  'Benson St',
  'Bergin Dr',
  'Berlin St',
  'Bernard Dr',
  'Bernard St',
  'Berry Ave',
  'Berry St',
  'Bessemer Park',
  'Bethel St',
  'Bigelow Rd',
  'Billings Rd',
  'Bilotta Way',
  'Birch St',
  'Birch St Ext',
  'Birch St Passway',
  'Birchwood Dr',
  'Bishop Rd',
  'Blackberry Ln',
  'Blake St',
  'Blanchard St',
  'Bliss Ave',
  'Bliss St',
  'Blossom St',
  'Blueberry Ln',
  'Bluff Ave',
  'Bobbin Hill Rd',
  'Bodge Ct',
  'Bodio Cir',
  'Bond St',
  'Bonnie Ave',
  'Bonnie Vista Ave',
  'Booth Rd',
  'Boston Hill Rd',
  'Boston St',
  'Boston St Ext',
  'Boulder Dr',
  'Bourque Ter',
  'Boutelle St',
  'Boutelle St Ext',
  'Boxwood Cir',
  'Boyle Ct',
  'Boylston St',
  'Bradford St',
  'Brandon Ave',
  'Bray Ave',
  'Bremer St',
  'Brigham Park',
  'Brigham St',
  'Brittany Ln',
  'Broad St',
  'Broadway',
  'Brook St',
  'Brookline St',
  'Brooks Ave',
  'Brown Ave',
  'Brown Rd',
  'Brown Rd Ext',
  'Bruce St',
  'Brunell Ave',
  'Bryan Rd',
  'Buckley Ave',
  'Buckley Ave Ext',
  'Buffum St',
  'Burgess St',
  'Burgess St Ext',
  'Burma Rd',
  'Burnap St',
  'Burns Ct',
  'Burns St',
  'Burnt Hill Rd',
  'Burrage Ave',
  'Burroughs Rd',
  'Butler Ave',
  'Butler St',
  'Buttrick Ave',
  'Cady St',
  'Cahill Pl',
  'Calvin St',
  'Cambridge St',
  'Camden St',
  'Camp St',
  'Canal St',
  'Candia St',
  'Candlewood Dr',
  'Candlestick Ln',
  'Cannon Cir',
  'Canton St',
  'Carlson St',
  'Carlton St',
  'Carmelita Ave',
  'Caron Ave',
  'Caron Cir',
  'Carriage Dr',
  'Carroll St',
  'Carson St',
  'Carter St',
  'Cartwright Ln',
  'Carver Rd',
  'Cass Ave',
  'Cassidy Ave',
  'Cassidy Ave Ext',
  'Castle St',
  'Castlewood Park',
  'Catalpa Rd',
  'Catholic Hill Rd',
  'Cecile Ave',
  'Celia St',
  'Central Ave',
  'Central Pl',
  'Central St',
  'Chaffee Ave',
  'Chaffee Ave Ext',
  'Chaffee Pl',
  'Chamberlain Ave',
  'Chamberlain Pkwy',
  'Chandler St',
  'Chapel St',
  'Chapman Pl',
  'Charette Ln',
  'Charles St',
  'Charles St Passway',
  'Charles St Rear',
  'Charlton St',
  'Charlton St Ext',
  'Charnock St',
  'Charter Rd',
  'Chase Ave',
  'Chase Rd',
  'Chase St',
  'Chasm St',
  'Chateau Dr',
  'Chatham Cir',
  'Chauncey Ave',
  'Chenery St',
  'Cherry Ct',
  'Cherry St',
  'Cherry St Ext',
  'Chestnut St',
  'Chestnut St Ext',
  'Chestnut St Passway',
  'Chickatawbut Rd',
  'Chilson Ave',
  'Chilson Ave Ext',
  'Chilson Ct',
  'Chippewa Dr',
  'Chippewa Dr Ext',
  'Chippewa Dr Passway',
  'Choate St',
  'Church Pl',
  'Church St',
  'Churchill St',
  'Circle St',
  'Clark Ave',
  'Clark Rd',
  'Clark St',
  'Clark St Ext',
  'Clarkson St',
  'Clarendon St',
  'Clarendon St Ext',
  'Clay Pl',
  'Clay St',
  'Clifford Pl',
  'Clifford St',
  'Clifton St',
  'Clifton St Ext',
  'Cloutier Dr',
  'Clough Ave',
  'Clover Cir',
  'Clovis St',
  'Clyde St',
  'Coburn Ave',
  'Coburn Ave Ext',
  'Coburn Pl',
  'Coburn St',
  'Cogswell St',
  'Colby Ave',
  'Cole Ave',
  'Colfax St',
  'Collette St',
  'Collins Ave',
  'Colman St',
  'Colton Ave',
  'Columbia Ave',
  'Columbus Ave',
  'Comet Cir',
  'Commerce Rd',
  'Comstock Ave',
  'Concord Ave',
  'Cone Ave',
  'Cone Ave Ext',
  'Congress St',
  'Congress St Ext',
  'Connell St',
  'Connor St',
  'Connors St',
  'Constellation Ave',
  'Constitution Ave',
  'Conway St',
  'Coolidge Ave',
  'Cooper St',
  'Coppage Dr',
  'Corbett Rd',
  'Corcoran Ave',
  'Cork Cir',
  'Cornelia St',
  'Coronado St',
  'Cortland St',
  'Cote Ave',
  'Cottage St',
  'Cottage St Passway',
  'Cottage St Rear',
  'Coulter Rd',
  'Courtland St',
  'Couture St',
  'Coventry St',
  'Cowdin Rd',
  'Cox St',
  'Cox St Ext',
  'Coy St',
  'Craig Pl',
  'Craig St',
  'Cranberry Hill Rd',
  'Crescent St',
  'Crestview Dr',
  'Crocker Hill Rd',
  'Crocker Rd',
  'Crocker Ter',
  'Cross St',
  'Crowley Ave',
  'Crystal St',
  'Cummings Ave',
  'Cummings Ave Ext',
  'Cummings St',
  'Cummings St Ext',
  'Curtis St',
  'Cutler Ave',
  'Dahl Ave',
  'Daly Ave',
  'Dana Rd',
  'Daniels St',
  'Danjo Dr',
  'Dart St',
  'Davenport St',
  'Davis Ave',
  'Davis St',
  'Day Pl',
  'Dean Ave',
  'Dean Hill Rd',
  'Dean St',
  'Deane Ave',
  'Deane St',
  'Deborah Rd',
  'Deerfield Ln',
  'Delisle Ave',
  'Dell St',
  'Delmont Ave',
  'Dennis St',
  'Denny St',
  'Derby St',
  'Derby St Ext',
  'Derby St Rear',
  'Desmond Dr',
  'Devereaux St',
  'Devine Ave',
  'Dexter Ave',
  'Dexter St',
  'Dickens St',
  'Dickinson Dr',
  'Dickson Ave',
  'Dickson Pl',
  'Dillon Dr',
  'Dixon St',
  'Doane St',
  'Dobson Ave',
  'Dodson Ave',
  'Dogwood Dr',
  'Donald Ave',
  'Donna Ave',
  'Donovan Ct',
  'Dora St',
  'Doreen St',
  'Dorothy Ave',
  'Douglas Ave',
  'Douglas Rd',
  'Dover St',
  'Downey St',
  'Doyle Ave',
  'Doyle St',
  'Draper St',
  'Drew Ave',
  'Drury Ln',
  'Dryden Ave',
  'Dublin St',
  'Ducharme Ave',
  'Duck Mill Rd',
  'Dudley St',
  'Dumas Ave',
  'Dunbar St',
  'Dunbar St Ext',
  'Dunn St',
  'Dunton Ave',
  'Dustin St',
  'Dwight Ave',
  'Dwight St',
  'Dyke St',
  'Eagle St',
  'East Ave',
  'East St',
  'East St Ext',
  'Eastwood Cir',
  'Eaton Ave',
  'Eddy St',
  'Edgell St',
  'Edgell St Ext',
  'Edward St',
  'Egan Ave',
  'Elaine St',
  'Eleanor St',
  'Elena Ave',
  'Elizabeth St',
  'Ella Ave',
  'Elm Ave',
  'Elm Ct',
  'Elm St',
  'Elm St Ext',
  'Elmhurst Ave',
  'Elmwood Ave',
  'Elmwood Park',
  'Elroy Ave',
  'Elwin St',
  'Emerald Ave',
  'Emerald Pl',
  'Emerson Pl',
  'Emerson St',
  'Emerson St Ext',
  'Empire St',
  'Endicott Ave',
  'Endicott St',
  'Erickson Ave',
  'Erline St',
  'Ernest St',
  'Essex St',
  'Essex St Ext',
  'Esterbrook Rd',
  'Ethel Ave',
  'Euclid Ave',
  'Euclid St',
  'Eustis St',
  'Evans St',
  'Everett Ave',
  'Evergreen Ave',
  'Evergreen St',
  'Exeter St',
  'Fabiano Dr',
  'Fairbanks St',
  'Fairbanks St Ext',
  'Fairmount St',
  'Fairview Rd',
  'Fairview St',
  'Falcon St',
  'Fallon St',
  'Farley Ave',
  'Farnsworth St',
  'Farrell St',
  'Farwell St',
  'Fassett St',
  'Fayette St',
  'Fayette St Ext',
  'Federal St',
  'Felton St',
  'Fenwick Pl',
  'Fern St',
  'Fernald St',
  'Ferrin St',
  'Ferry St',
  'Field Ave',
  'Field St',
  'Fifth Mass Tpke Ext',
  'Fifth Mass Tpke Passway',
  'Fifth Mass Turnpike',
  'Fifth St',
  'Filmore Ave',
  'Fisher Rd',
  'Fitch Hill Ave',
  'Fitch St',
  'Fitchburg Access Rd',
  'Fitchburg Rd',
  'Fitchburg St',
  'Fitchburg State College Access',
  'Fitchburg State College Rd',
  'Fitchburg Tpke',
  'Fitchburg Tpke Ext',
  'Fitchburg Tpke Passway',
  'Fitzgerald Ave',
  'Fitzpatrick Rd',
  'Flagg St',
  'Fleetwood Dr',
  'Flint Ave',
  'Flora Ave',
  'Floral St',
  'Florence St',
  'Florence St Ext',
  'Foley St',
  'Folsom St',
  'Forest Ave',
  'Forest Pl',
  'Forest St',
  'Forest St Ext',
  'Forrest Ave',
  'Forsythia Dr',
  'Foster St',
  'Fountain St',
  'Fourth St',
  'Fox St',
  'Frank St',
  'Franklin Rd',
  'Franklin Rd Ext',
  'Franklin St',
  'Franklin St Ext',
  'Fredette St',
  'Freeman Ave',
  'French Ave',
  'French St',
  'Friendship Cir',
  'Front St',
  'Frye Rd',
  'Fuller Rd',
  'Fulton St',
  'Hadwen Rd',
  'Hale St',
  'Hall Ave',
  'Hall St',
  'Hall St Ext',
  'Hall St Passway',
  'Hall St Rear',
  'Hallberg Ave',
  'Hallett St',
  'Hallmark Hill Dr',
  'Hallock St',
  'Hallwood Dr',
  'Hamilton St',
  'Hammond St',
  'Hampshire St',
  'Hancock St',
  'Handel Rd',
  'Hanover St',
  'Hanson St',
  'Happy Hollow Rd',
  'Harding St',
  'Hardy Passway',
  'Hardy St',
  'Harlow St',
  'Harriet St',
  'Harrington St',
  'Harris Ave',
  'Harrison Ave',
  'Hart St',
  'Hartwell St',
  'Harvard St',
  'Harwood Rd',
  'Hastings Ave',
  'Hatch Rd',
  'Hathaway Rd',
  'Hathaway St',
  'Haven St',
  'Hawes St',
  'Hawthorne St',
  'Hayes St',
  'Hayward St',
  'Hazel St',
  'Hazel St Ext',
  'Hector St',
  'Hemlock Dr',
  'Hemlock Ln',
  'Henderson St',
  'Henry Ave',
  'Henry St',
  'Herbert St',
  'Heritage Ln',
  'Herman Ave',
  'Hersey Rd',
  'Hesper St',
  'Hewitt Dr',
  'Hickory Dr',
  'High Rock Rd',
  'High Rock Ter',
  'High St',
  'High St Ext',
  'High St Passway',
  'Highland Ave',
  'Highland Ave Ext',
  'Highland St',
  'Hill St',
  'Hillcrest Rd',
  'Hilltop Dr',
  'Hitchcock Rd',
  'Hobson St',
  'Hodgkins Rd',
  'Hoffman Ave',
  'Hollis Ave',
  'Hollis Hill Rd',
  'Hollywood St',
  'Holman St',
  'Holmes St',
  'Holy Family Rd',
  'Homer Ave',
  'Honeybee Ln',
  'Hooker St',
  'Hope St',
  'Hopkins Rd',
  'Hosmer St',
  'Houston St',
  'Howard Ave',
  'Howard St',
  'Howland Rd',
  'Howland Ter',
  'Hubbardston Rd',
  'Hudson St',
  'Hugh St',
  'Hull St',
  'Humiston Ave',
  'Hunt St',
  'Hunter Ave',
  'Huntington St',
  'Huron Ave',
  'Hutchinson St',
  'Idlewood Cir',
  'Indian Hill Ave',
  'Indian Hill Rd',
  'Indian Hill Ter',
  'Industrial Rd',
  'Ingraham Hill Rd',
  'Inman Ave',
  'Interstate 190 (I-190)',
  'Irving St',
  'Isabel Ave',
  'Island Ave',
  'Island Rd',
  'Iver Johnson Pl',
  'Iverson St',
  'Jackson Ave',
  'Jackson Ave Ext',
  'Jackson Ave Passway',
  'Jackson Ave Rear',
  'Jackson St',
  'Jacobs Rd',
  'Jacques St',
  'James St',
  'James St Ext',
  'Janice Ave',
  'Jarvis Rd',
  'Jason Ave',
  'Jefferson St',
  'Jefferson St Ext',
  'Jefferson St Rear',
  'Jenks Rd',
  'Jennison Rd',
  'Jenny St',
  'Jerome Ave',
  'Jessie Ave',
  'Jill Rd',
  'Joan Ave',
  'Joe Ave',
  'John Fitch Hwy',
  'John St',
  'Johnson Ave',
  'Johnson St',
  'Johnsonia Ave',
  'Jordan Rd',
  'Joseph Rd',
  'Joslin St',
  'Judith Ave',
  'Jules St',
  'June St',
  'Junction Rd',
  'Juniper Rd',
  'Kane Ave',
  'Karen Dr',
  'Karlene St',
  'Karns Rd',
  'Katherine Ave',
  'Kathleen Dr',
  'Katie St',
  'Kendall Rd',
  'Kent St',
  'Kenwood Rd',
  'Kerry Ave',
  'Kettle Rd',
  'Kevin Rd',
  'Keyes St',
  'Kimball St',
  'Kimball St Ext',
  'King St',
  'Kingsbury St',
  'Kingsbury St Ext',
  'Kingsbury St Rear',
  'Kingsman Ave',
  'Kinsley Ave',
  'Kirk St',
  'Kittredge Rd',
  'Knollwood Dr',
  'Knowlton Rd',
  'Knox Ave',
  'Knox Pl',
  'Knox St',
  'Kossuth St',
  'Kramer Rd',
  'Kuhn Rd',
  'Lafayette St',
  'Lake Ave',
  'Lake St',
  'Lake St Ext',
  'Lakeview Ave',
  'Lamson Ave',
  'Lancaster Pl',
  'Lancaster St',
  'Lancaster St Ext',
  'Lane Ave',
  'Langley St',
  'Lanides Ln',
  'Lanides Ln Ext',
  'Larch St',
  'Larkin Ave',
  'Larned Rd',
  'Laurel St',
  'Lawton Pl',
  'Lawton St',
  'Lawton St Ext',
  'Leahy Ave',
  'Leary Ave',
  'LeBlanc St',
  'Lee Ave',
  'Lee St',
  'Legros Ave',
  'Leighton St',
  'Leighton St Ext',
  'Lemay Ave',
  'Lenox St',
  'Lepine Ave',
  'Levesque St',
  'Lewis St',
  'Lexington St',
  'Liberty Ave',
  'Liberty St',
  'Lillian Ave',
  'Lincoln St',
  'Linda St',
  'Linda St Ext',
  'Linda St Passway',
  'Lindell Ave',
  'Lindell Ave Ext',
  'Lindley Rd',
  'Lindsey St',
  'Linwood Ave',
  'Linwood Ave Ext',
  'Lions Ave',
  'Littlejohn Ave',
  'Livingston St',
  'Locke Dr',
  'Locke Rd',
  'Locke St',
  'Lockwood Cir',
  'Log Cabin Rd',
  'Lomond Pl',
  'Lonsdale St',
  'Lorrain St',
  'Lorraine Ave',
  'Lost Lake Rd',
  'Louis Ave',
  'Lowell St',
  'Lowell St Ext',
  'Lowell St Passway',
  'Lowell St Rear',
  'Lucinda Ave',
  'Lucinda Passway',
  'Lucy Ave',
  'Lundberg Ave',
  'Lundberg St',
  'Lundgren Ave',
  'Luther Pl',
  'Lyman Ave',
  'Lynde Ave',
  'Lynde St',
  'Lynwood Ave',
  'MacAlister Dr',
  'Mack Ave',
  'Madison Ave',
  'Madison St',
  'Madonna Dr',
  'Mahoney Ave',
  'Main St',
  'Main St Ext',
  'Main St Passway',
  'Main St Rear',
  'Manning Ave',
  'Maple Ave',
  'Maple St',
  'Maplewood Ave',
  'Marble St',
  'Marcelle St',
  'Marie Ave',
  'Marie Ave Ext',
  'Marie Ave Passway',
  'Marina Ave',
  'Marion St',
  'Marion St Ext',
  'Market St',
  'Marquette St',
  'Marshall St',
  'Marshall St Ext',
  'Marshall St Passway',
  'Marshall St Rear',
  'Martin Ave',
  'Martin Ave Ext',
  'Martin St',
  'Martin St Ext',
  'Mary Ave',
  'Mason Rd',
  'Mason St',
  'Mason St Ext',
  'Mason St Rear',
  'Massachusetts Ave',
  'Massasoit St',
  'Matthews St',
  'Maxwell Ave',
  'May Pl',
  'Mayfield Rd',
  'Maynard St',
  'Maywood Ave',
  'McCabe Ave',
  'McDonough Ave',
  'McDonough Dr',
  'McIntire Rd',
  'McKay Ave',
  'McKay Ave Ext',
  'McKay Ave Passway',
  'McKay Ave Rear',
  'Meadow Ln',
  'Meadow St',
  'Meadowbrook Ln',
  'Mechanic St',
  'Mechanic St Ext',
  'Mechanic St Passway',
  'Mechanic St Rear',
  'Melrose St',
  'Melvin Ave',
  'Mendon St',
  'Mercier Blvd',
  'Meredith St',
  'Meriam Ave',
  'Merriam Ave',
  'Merriam Pkwy',
  'Merrill St',
  'Merritt Rd',
  'Merton Rd',
  'Metcalf Ave',
  'Metcalf St',
  'Michael Dr',
  'Michigan Ave',
  'Middle St',
  'Middle St Ext',
  'Middle St Rear',
  'Middlesex St',
  'Midland St',
  'Midland St Ext',
  'Midland St Rear',
  'Miles Ave',
  'Mill St',
  'Mill St Ext',
  'Mill St Passway',
  'Mill St Rear',
  'Millard Ave',
  'Milton Ave',
  'Milton St',
  'Mitchell Ave',
  'Mitchell St',
  'Monroe St',
  'Montachusett Ave',
  'Montachusett Rd',
  'Montgomery St',
  'Montville St',
  'Moore St',
  'Mooreland St',
  'Moran Ave',
  'Moran Ct',
  'Morgan Ave',
  'Morin Ave',
  'Morris Ave',
  'Morse Ave',
  'Morton St',
  'Mount Elam Rd',
  'Mount Vernon St',
  'Mount Vernon St Ext',
  'Mowry St',
  'Mulberry St',
  'Mulligan St',
  'Munroe St',
  'Murphy Ave',
  'Murray Ave',
  'Myrtle Ave',
  'Myrtle St',
  'Nashua St',
  'Nashua St Ext',
  'Nashua St Passway',
  'Nashua St Rear',
  'Nashua Tpke',
  'Nashua Tpke Ext',
  'Nashua Tpke Passway',
  'Nashua Tpke Rear',
  'Nathan Dr',
  'National Grid Access Rd',
  'Nelson Ave',
  'Nelson St',
  'Nelson St Ext',
  'Nelson St Passway',
  'Nelson St Rear',
  'New West Townsend Rd',
  'Newton Pl',
  'Newton St',
  'Newton St Ext',
  'Newton St Passway',
  'Newton St Rear',
  'Nichols St',
  'Nichols St Ext',
  'Nichols St Passway',
  'Nichols St Rear',
  'Nickerson Rd',
  'Nightingale Ave',
  'Ninth St',
  'Nixon Rd',
  'Noble Ave',
  'Nolan Ter',
  'Norcross Ave',
  'Norcross St',
  'North St',
  'Northfield St',
  'Northside Pkwy',
  'Norway St',
  'Noyes St',
  'Noyes St Ext',
  'Nye Ave',
  'O’Brien Rd',
  'O’Connor Dr',
  'Oak Ave',
  'Oak Hill Rd',
  'Oak St',
  'Oak St Ext',
  'Oakland St',
  'Oaklawn Ave',
  'Oakwood Ave',
  'Odell Rd',
  'Ogden St',
  'Ohio Ave',
  'Old City Hall Access Rd',
  'Old Deerfield Rd',
  'Old Princeton Rd',
  'Old Westminster Rd',
  'Oliver St',
  'Oliver St Ext',
  'Oliver St Passway',
  'Oliver St Rear',
  'Olsen St',
  'Onedia St',
  'Orange St',
  'Orchard Ave',
  'Orchard Ln',
  'Orchard St',
  'Oriole St',
  'Osborn Rd',
  'Osborn St',
  'Overlook Dr',
  'Oxford St',
  'Pacific St',
  'Page Ave',
  'Palmer Ave',
  'Palmer Rd',
  'Paradise St',
  'Pariseau Ave',
  'Park Pl',
  'Park Pl Ext',
  'Park St',
  'Park St Ext',
  'Park St Passway',
  'Parker Rd',
  'Parmenter St',
  'Parsons St',
  'Pasquale Ave',
  'Patten St',
  'Paul Ave',
  'Pauline Ave',
  'Pearl Hill Park Rd',
  'Pearl Hill Rd',
  'Pearl Hill St',
  'Pearl Hill St Ext',
  'Pearl St',
  'Pease Ave',
  'Peckham Ave',
  'Peckham St',
  'Pelletier Ave',
  'Penn Ave',
  'Pennington Ave',
  'Perkins St',
  'Perkins St Ext',
  'Perrin Ave',
  'Perrin St',
  'Perrin St Ext',
  'Peters Rd',
  'Peterson Ave',
  'Peterson Dr',
  'Phillips St',
  'Phoenix St',
  'Pierce Ave',
  'Pierpont St',
  'Pike Ave',
  'Pine Ave',
  'Pine St',
  'Pine St Ext',
  'Pine St Passway',
  'Pine St Rear',
  'Pinewood Ave',
  'Pinewood Ave Ext',
  'Pinewood Ave Passway',
  'Pinewood Ave Rear',
  'Piper Rd',
  'Pitcairn Ave',
  'Pitman St',
  'Pittsburgh Ave',
  'Plain St',
  'Pleasant Ave',
  'Pleasant St',
  'Pleasant St Ext',
  'Pleasant St Passway',
  'Pleasant St Rear',
  'Plum St',
  'Pond St',
  'Pond St Ext',
  'Pond St Passway',
  'Pond St Rear',
  'Pond View Dr',
  'Pope Rd',
  'Poplar St',
  'Porter St',
  'Portland St',
  'Portland St Ext',
  'Portland St Rear',
  'Post Rd',
  'Powell St',
  'Pratt Rd',
  'Pratt St',
  'Pratt St Ext',
  'Prescott St',
  'Prescott St Ext',
  'Prescott St Passway',
  'Prescott St Rear',
  'Preston Ave',
  'Preston St',
  'Princeton Rd',
  'Prospect St',
  'Prospect St Ext',
  'Prospect St Passway',
  'Prospect St Rear',
  'Providence St',
  'Providence St Ext',
  'Providence St Passway',
  'Providence St Rear',
  'Puffer St',
  'Pulaski St',
  'Putnam Pl',
  'Putnam St',
  'Quail Run',
  'Quarry Ln',
  'Quarry Rd',
  'Quebec St',
  'Queen St',
  'Quimby Ave',
  'Quincy Ave',
  'Quincy St',
  'Quinn Rd',
  'Quinn St',
  'Quinns Pl',
  'Quinns Rd',
  'Quinns St',
  'Rachael Ter',
  'Railroad Ave',
  'Railroad St',
  'Ralph Ave',
  'Ralph St',
  'Ramsey Ave',
  'Randall Rd',
  'Randolph Rd',
  'Ravenelle Rd',
  'Ray Ave',
  'Ray Ave Ext',
  'Ray Ave Passway',
  'Ray Ave Rear',
  'Raymond St',
  'Redwood Ave',
  'Reed St',
  'Reid St',
  'Remington St',
  'Renwick Rd',
  'Republic Ave',
  'Revere St',
  'Reynolds Ave',
  'Reynolds St',
  'Rice Ave',
  'Rice Hill Rd',
  'Rice St',
  'Rich St',
  'Richard Ave',
  'Richardson Ave',
  'Richardson Ave Ext',
  'Richmond Ave',
  'Richview Ave',
  'Ridge Ave',
  'Ridge St',
  'Ridgewood Rd',
  'Riley Ave',
  'Rindge Rd',
  'Rindge Rd Ext',
  'Rita Ave',
  'River St',
  'Riverbank Ter',
  'Riverfront Dr',
  'Riverside Ave',
  'Riverside Rd',
  'Riverview Ave',
  'Robert Ave',
  'Robinson Ave',
  'Robinson St',
  'Robinson St Ext',
  'Robinson St Passway',
  'Robinson St Rear',
  'Robinsonville Ave',
  'Rochester St',
  'Rock Hill Rd',
  'Rockland St',
  'Rockland St Ext',
  'Rockland St Rear',
  'Rocky Hill Rd',
  'Rocky Hill Rd Ext',
  'Rodgers Ave',
  'Rodney St',
  'Rogers Ave',
  'Rogers Rd',
  'Roper St',
  'Ross Ave',
  'Ross St',
  'Round Hill Rd',
  'Round Rock Rd',
  'Rowell Ave',
  'Royal Crest Dr',
  'Royalston Rd',
  'Royalston Rd Ext',
  'Ruby St',
  'Russell Ave',
  'Russell St',
  'Russell St Ext',
  'Russell St Rear',
  'Ruth St',
  'Ryan St',
  'Sacramento St',
  'Sacramento St Ext',
  'Safford Ave',
  'Salem St',
  'Salem St Ext',
  'Salem St Passway',
  'Salem St Rear',
  'Salem Tpke Ext',
  'Salem Tpke Passway',
  'Salem Tpke Rear',
  'Salem Turnpike',
  'Saliba Ave',
  'Salman St',
  'Samoset Ave',
  'Sanborn St',
  'Sanders Rd',
  'Sanderson St',
  'Sanderson St Ext',
  'Sanderson St Passway',
  'Sanderson St Rear',
  'Sanderson Ter',
  'Sanford St',
  'Sanford St Ext',
  'Sanford St Rear',
  'Sargent Ave',
  'Sargent Rd',
  'Sargent St',
  'Sargent St Ext',
  'Sargent St Passway',
  'Sargent St Rear',
  'Sargent Ter',
  'Sartell Rd',
  'Saulnier St',
  'Sawyer Passway',
  'Sawyer St',
  'Scales Ln',
  'School St',
  'School St Ext',
  'School St Passway',
  'School St Rear',
  'Scott Rd',
  'Scott St',
  'Scott St Ext',
  'Scott St Passway',
  'Scott St Rear',
  'Scribner Rd',
  'Seaver Rd',
  'Second St',
  'Selby Ave',
  'Senna Ter',
  'Seven Hills Rd',
  'Seventh St',
  'Shady Ave',
  'Shattuck St',
  'Shea St',
  'Sheffield Pl',
  'Sheffield Rd',
  'Sheldon Rd',
  'Shepard Ave',
  'Shepard St',
  'Sherburne Ave',
  'Sherman Ave',
  'Sherman St',
  'Sherwin Ter',
  'Shirley St',
  'Shirley St Ext',
  'Shirley St Passway',
  'Shirley St Rear',
  'Shirley Tpke Ext',
  'Shirley Tpke Passway',
  'Shirley Tpke Rear',
  'Shirley Turnpike',
  'Short St',
  'Shrewsbury St',
  'Shurtleff Ave',
  'Sibley St',
  'Sicard St',
  'Sierra St',
  'Silver St',
  'Silver St Ext',
  'Silver St Passway',
  'Silver St Rear',
  'Simeon Rd',
  'Simon St',
  'Sims Ave',
  'Sixth St',
  'Slade Ave',
  'Slade St',
  'Slattery Ln',
  'Slocum St',
  'Smith Ave',
  'Smith Ave Ext',
  'Smith Ave Passway',
  'Smith Ave Rear',
  'Smith St',
  'Smith St Ext',
  'Smith St Passway',
  'Smith St Rear',
  'Snow St',
  'Snow St Ext',
  'Snow St Passway',
  'Snow St Rear',
  'South St',
  'South St Ext',
  'South St Passway',
  'South St Rear',
  'Southby Rd',
  'Southwick Ave',
  'Southwick Ter',
  'Spaulding St',
  'Spaulding St Ext',
  'Spaulding St Passway',
  'Spaulding St Rear',
  'Spring Ave',
  'Spring Hill Ave',
  'Spring St',
  'Spring St Ext',
  'Spring St Passway',
  'Spring St Rear',
  'Springdale Rd',
  'Spruce St',
  'Spruce St Ext',
  'Spruce St Passway',
  'Spruce St Rear',
  'St Anna St',
  'St Bernard’s St',
  'St Cecelia St',
  'St Elmo Rd',
  'St John St',
  'St Joseph Ave',
  'St Joseph Ave Ext',
  'St Joseph Ave Passway',
  'St Joseph Ave Rear',
  'St Joseph St',
  'St Joseph St Ext',
  'St Joseph St Passway',
  'St Joseph St Rear',
  'St Martin Ave',
  'St Peter St',
  'St Peter St Ext',
  'St Peter St Passway',
  'St Peter St Rear',
  'Stafford St',
  'Stanton St',
  'Staples Ave',
  'Starling Ave',
  'State St',
  'State St Ext',
  'State St Passway',
  'State St Rear',
  'Sterling St',
  'Sterling St Ext',
  'Sterling St Passway',
  'Sterling St Rear',
  'Stevens Rd',
  'Stevenson Rd',
  'Stillman Ave',
  'Stockwell Ave',
  'Stoneleigh Rd',
  'Stoneleigh Rd Ext',
  'Stoneleigh Ter',
  'Stoneybrook Rd',
  'Stoneybrook Rd Ext',
  'Stonybrook Rd',
  'Stoughton Ln',
  'Stratton Dr',
  'Strong Ave',
  'Strong St',
  'Strong St Ext',
  'Strong St Passway',
  'Strong St Rear',
  'Stuart Ave',
  'Summer St',
  'Summer St Ext',
  'Summer St Passway',
  'Summer St Rear',
  'Summit St',
  'Summit St Ext',
  'Summit St Passway',
  'Summit St Rear',
  'Sunnyside Ave',
  'Sunset Ave',
  'Sunset Ave Ext',
  'Sunset Ave Passway',
  'Sunset Ave Rear',
  'Sunset Rd',
  'Superior Ave',
  'Superior Ave Ext',
  'Superior Ave Passway',
  'Superior Ave Rear',
  'Sutcliffe Ave',
  'Sutton Rd',
  'Sylvia St',
  'Taft St',
  'Talbot Ave',
  'Talbot Ave Ext',
  'Talbot Ave Passway',
  'Talbot Ave Rear',
  'Talbot St',
  'Talbot St Ext',
  'Talbot St Passway',
  'Talbot St Rear',
  'Tall Pines Dr',
  'Talman St',
  'Tammie St',
  'Tanglewood Dr',
  'Tanner St',
  'Tarbell St',
  'Tatra Dr',
  'Taylor St',
  'Taylor St Ext',
  'Taylor St Passway',
  'Taylor St Rear',
  'Temple St',
  'Temple St Ext',
  'Temple St Passway',
  'Temple St Rear',
  'Tenney St',
  'Tennyson St',
  'Terrace Pl',
  'Terrace St',
  'Terrace St Ext',
  'Terrace St Passway',
  'Terrace St Rear',
  'Terrill Ave',
  'Thayer Ave',
  'Thayer St',
  'Thayer St Ext',
  'Thayer St Passway',
  'Thayer St Rear',
  'Third St',
  'Thomas St',
  'Thomas St Ext',
  'Thomas St Passway',
  'Thomas St Rear',
  'Thompson Ave',
  'Thompson Rd',
  'Thompson St',
  'Thompson St Ext',
  'Thompson St Passway',
  'Thompson St Rear',
  'Thornton Ave',
  'Thornton St',
  'Thornton St Ext',
  'Thornton St Passway',
  'Thornton St Rear',
  'Thurston St',
  'Thurston St Ext',
  'Thurston St Passway',
  'Thurston St Rear',
  'Tibbets Rd',
  'Ticonderoga Dr',
  'Tiffany Ave',
  'Tilden St',
  'Tilden St Ext',
  'Tilden St Passway',
  'Tilden St Rear',
  'Tillotson Rd',
  'Tilton Ave',
  'Tilton St',
  'Tilton St Ext',
  'Tilton St Passway',
  'Tilton St Rear',
  'Titus Ave',
  'Tobin Ave',
  'Tolland Dr',
  'Tolman St',
  'Tolman St Ext',
  'Tolman St Passway',
  'Tolman St Rear',
  'Tom Dr',
  'Torry St',
  'Towne Ave',
  'Townsend Pl',
  'Townsend St',
  'Townsend St Ext',
  'Townsend St Passway',
  'Townsend St Rear',
  'Trafalgar Sq',
  'Trafalgar Ter',
  'Trask St',
  'Tremont St',
  'Tremont St Ext',
  'Tremont St Passway',
  'Tremont St Rear',
  'Tricia Ave',
  'Trinidad Ave',
  'Trinity St',
  'Trowbridge St',
  'Troy St',
  'Truax Rd',
  'Trull Ave',
  'Turner Ave',
  'Turner Ave Ext',
  'Turner Ave Passway',
  'Turner Ave Rear',
  'Turnpike Rd',
  'Twelfth St',
  'Tyler Ave',
  'Tyler St',
  'Union Pl',
  'Union St',
  'Union St Ext',
  'Union St Passway',
  'Union St Rear',
  'Unity Ave',
  'Upland St',
  'Upper Common',
  'Upton St',
  'Vale St',
  'Valentine St',
  'Valera St',
  'Valeri Ave',
  'Valhalla Dr',
  'Valley Ave',
  'Valley St',
  'Valley St Ext',
  'Valley St Passway',
  'Valley St Rear',
  'Van Dyke St',
  'Van Wert Ave',
  'Vassar St',
  'Vassar St Ext',
  'Vassar St Passway',
  'Vassar St Rear',
  'Vega Rd',
  'Vermont Ave',
  'Vernon Ave',
  'Vernon St',
  'Vernon St Ext',
  'Vernon St Passway',
  'Vernon St Rear',
  'Veronica Ave',
  'Veronica Ave Ext',
  'Veronica Ave Passway',
  'Veronica Ave Rear',
  'Victoria Ave',
  'Victory St',
  'Victory St Ext',
  'Victory St Passway',
  'Victory St Rear',
  'View St',
  'Village St',
  'Vine St',
  'Violet St',
  'Virginia Ave',
  'Virginia Ave Ext',
  'Virginia Ave Passway',
  'Virginia Ave Rear',
  'Vose Rd',
  'Vose St',
  'Wachusett Dr',
  'Wachusett St',
  'Wachusett St Ext',
  'Wachusett St Passway',
  'Wachusett St Rear',
  'Wadleigh Ave',
  'Waldo St',
  'Walker Rd',
  'Walker St',
  'Wallace Ave',
  'Wallace Ave Ext',
  'Wallace Ave Passway',
  'Wallace Ave Rear',
  'Wallace St',
  'Wallace St Ext',
  'Wallace St Passway',
  'Wallace St Rear',
  'Wallingford St',
  'Walnut St',
  'Walnut St Ext',
  'Walnut St Passway',
  'Walnut St Rear',
  'Waltham St',
  'Walton St',
  'Wanamaker Rd',
  'Wanda St',
  'Ward St',
  'Wardell Ct',
  'Ware St',
  'Warner Ave',
  'Warren St',
  'Washington Ave',
  'Washington St',
  'Washington St Ext',
  'Washington St Passway',
  'Washington St Rear',
  'Water St',
  'Water St Ext',
  'Water St Passway',
  'Water St Rear',
  'Waterford St',
  'Waterloo St',
  'Watson Ave',
  'Watson Pl',
  'Watson St',
  'Watson St Ext',
  'Watson St Passway',
  'Watson St Rear',
  'Watts St',
  'Wayne Ave',
  'Webber St',
  'Webster Rd',
  'Webster St',
  'Weed St',
  'Weldon St',
  'Wellman St',
  'Wendell Ave',
  'Wentworth Ave',
  'West St',
  'West St Ext',
  'West St Passway',
  'West St Rear',
  'Westminster Hill Rd',
  'Westminster St',
  'Westminster St Ext',
  'Westminster St Passway',
  'Westminster St Rear',
  'Westview Dr',
  'Westwood Dr',
  'Whalon St',
  'Whalon St Ext',
  'Whalon St Passway',
  'Whalon St Rear',
  'Whipple St',
  'Whitcomb St',
  'White St',
  'White St Ext',
  'White St Passway',
  'White St Rear',
  'Whitin Ave',
  'Whiting Ave',
  'Whittier St',
  'Wightman Ave',
  'Wild Rose Ln',
  'Wilder St',
  'Wildwood Rd',
  'Wilkins Rd',
  'Wilkins St',
  'Willard St',
  'Willard St Ext',
  'Willard St Passway',
  'Willard St Rear',
  'William St',
  'Williams Rd',
  'Williams St',
  'Williams St Ext',
  'Williams St Passway',
  'Williams St Rear',
  'Willow Ave',
  'Willow St',
  'Willow St Ext',
  'Willow St Passway',
  'Willow St Rear',
  'Wilson Ave',
  'Wilson Ave Ext',
  'Wilson Ave Passway',
  'Wilson Ave Rear',
  'Wilson St',
  'Wilson St Ext',
  'Wilson St Passway',
  'Wilson St Rear',
  'Winchester Ave',
  'Winchester Ave Ext',
  'Winchester Ave Passway',
  'Winchester Ave Rear',
  'Winding Way',
  'Windsor St',
  'Windsor St Ext',
  'Windsor St Passway',
  'Windsor St Rear',
  'Wing St',
  'Winifred Ave',
  'Winona Ave',
  'Winter St',
  'Winter St Ext',
  'Winter St Passway',
  'Winter St Rear',
  'Witch Rd',
  'Woburn St',
  'Wood Ave',
  'Wood Pl',
  'Wood St',
  'Wood St Ext',
  'Wood St Passway',
  'Wood St Rear',
  'Woodbury St',
  'Woodland St',
  'Woodlawn Ave',
  'Woodrow Ave',
  'Worcester Ave',
  'Worcester Rd',
  'Worcester St',
  'Worcester St Ext',
  'Worcester St Passway',
  'Worcester St Rear',
  'Wright Ave',
  'Yardley St',
  'Young Ave',
  'Young St',
  'Young St Ext',
  'Young St Passway',
  'Young St Rear',
  'Zeda Ave',
  'Zelman St',
  'Zion St',
  'Zion St Ext',
  'Zion St Passway',
  'Zion St Rear'
];

// List of streets in Gardner, MA
export const GARDNER_STREETS: string[] = [
  'Abbott Street',
  'Academy Street',
  'Aiken Avenue',
  'Albee Street',
  'Albion Street',
  'Albert Street',
  'Alexander Street',
  'Almond Street',
  'Almond Street Ext',
  'Alpine Street',
  'Alwine Street',
  'Amos Street',
  'Andover Street',
  'Appleton Street',
  'Arcade Street',
  'Arlington Street',
  'Armstrong Avenue',
  'Arthur Street',
  'Ashby Street',
  'Ashby Street Ext',
  'Ashby Street Passway',
  'Ashby Street Rear',
  'Ashby Terrace',
  'Ashfield Road',
  'Aspen Street',
  'Astor Street',
  'Athol Street',
  'Atlas Street',
  'Audubon Street',
  'Aurora Street',
  'Austin Street',
  'Avon Street',
  'Ayers Street',
  'Baldwin Street',
  'Ballard Avenue',
  'Bank Street',
  'Barlow Street',
  'Barnes Avenue',
  'Barron Street',
  'Bartlett Street',
  'Bartlett Street Ext',
  'Bartlett Street Passway',
  'Bartlett Street Rear',
  'Bass Avenue',
  'Bay State Street',
  'Becker Street',
  'Beckwith Street',
  'Beech Street',
  'Belcher Street',
  'Belmont Street',
  'Bemis Street',
  'Bennett Street',
  'Bennett Street Ext',
  'Benton Street',
  'Berkeley Street',
  'Bertrand Street',
  'Beverly Street',
  'Bigelow Street',
  'Birch Street',
  'Blackberry Street',
  'Blackstone Street',
  'Blanchard Street',
  'Bliss Street',
  'Blodgett Street',
  'Blossom Street',
  'Blueberry Lane',
  'Boggs Avenue',
  'Booth Street',
  'Boston Hill Road',
  'Boundary Street',
  'Bowditch Avenue',
  'Bowman Street',
  'Bradley Street',
  'Bradstreet Street',
  'Branch Street',
  'Brewster Street',
  'Bridge Street',
  'Bright Street',
  'Bristol Avenue',
  'Broad Street',
  'Broadway',
  'Brodie Street',
  'Brook Street',
  'Brown Avenue',
  'Brown Street',
  'Bruce Street',
  'Bryant Street',
  'Buckingham Street',
  'Buckley Street',
  'Buffum Street',
  'Bunker Street',
  'Burnap Street',
  'Burnham Street',
  'Burton Street',
  'Butler Street',
  'Byron Street',
  'Cable Street',
  'Calais Avenue',
  'Calais Road',
  'Caldwell Street',
  'Callahan Avenue',
  'Cambridge Street',
  'Cameron Avenue',
  'Camp Road',
  'Canary Street',
  'Canton Street',
  'Capen Avenue',
  'Carlton Street',
  'Carter Street',
  'Cassidy Street',
  'Castle Street',
  'Catherine Street',
  'Cavendish Street',
  'Cedar Street',
  'Cedar Street Ext',
  'Chamberlain Street',
  'Chance Street',
  'Chapel Street',
  'Charles Street',
  'Charter Street',
  'Chase Avenue',
  'Chase Street',
  'Chauncey Street',
  'Cheshire Street',
  'Chestnut Street',
  'Chestnut Street Ext',
  'Chestnut Street Front',
  'Chestnut Street Passway',
  'Chestnut Street Rear',
  'Chestnut Street Side',
  'Clarke Street',
  'Clarkson Street',
  'Cliff Street',
  'Clinton Street',
  'Clinton Street Ext',
  'Clinton Street Rear',
  'Cobb Street',
  'Cochrane Street',
  'Cole Avenue',
  'College Street',
  'Collins Street',
  'Colony Street',
  'Common Street',
  'Concord Street',
  'Congress Street',
  'Converse Street',
  'Cook Street',
  'Cooley Street',
  'Cooper Street',
  'Corbett Street',
  'Corliss Street',
  'Cornell Street',
  'Cortland Street',
  'Cortland Street Ext',
  'Cortland Street Passway',
  'Curtis Street',
  'Cushing Avenue',
  'Daggett Street',
  'Damon Street',
  'Dana Street',
  'Daniels Street',
  'Davenport Street',
  'Davis Street',
  'Day Street',
  'Dean Street',
  'Deane Avenue',
  'Deane Street',
  'Delano Street',
  'Demers Avenue',
  'Denison Street',
  'Dent Street',
  'Derby Street',
  'Dewey Street',
  'Dexter Street',
  'Diamond Street',
  'Dighton Street',
  'Dill Street',
  'Dixon Street',
  'Dodd Street',
  'Dodge Street',
  'Dolliver Street',
  'Dolphin Street',
  'Donovan Street',
  'Doolittle Street',
  'Doran Street',
  'Dover Street',
  'Dow Street',
  'Doyle Avenue',
  'Drake Street',
  'Drew Street',
  'Driscoll Avenue',
  'Driscoll Street',
  'Dudley Street',
  'Duffield Street',
  'Dunham Street',
  'Dunham Street Ext',
  'Dunn Street',
  'Dupee Street',
  'Durfee Street',
  'Dyer Street',
  'Eagle Street',
  'Easthampton Street',
  'Eastward Street',
  'Eaton Street',
  'Eddy Street',
  'Edgewood Street',
  'Edith Street',
  'Edmunds Street',
  'Elder Street',
  'Eliot Street',
  'Elm Street',
  'Elm Street Ext',
  'Elm Street Passway',
  'Elm Street Rear',
  'Elwood Street',
  'Emerson Street',
  'Emery Street',
  'Engine Lane',
  'Essex Street',
  'Estes Street',
  'Everett Street',
  'Fay Street',
  'Federal Street',
  'Felton Street',
  'Fenway Street',
  'Fern Street',
  'Field Street',
  'Fifth Street',
  'Fiske Street',
  'Fitchburg Street',
  'Flank Street',
  'Flanders Street',
  'Flint Street',
  'Florence Street',
  'Flower Street',
  'Fogg Street',
  'Foley Street',
  'Forbes Street',
  'Forest Avenue',
  'Forest Hill Road',
  'Forman Street',
  'Foster Street',
  'Fountain Street',
  'Fox Street',
  'Frances Street',
  'Francis Street',
  'Franklin Street',
  'Franklin Street Ext',
  'Franklin Street Rear',
  'Frederick Street',
  'Freeman Street',
  'French Street',
  'Frost Avenue',
  'Fuller Street',
  'Gage Street',
  'Gallagher Street',
  'Gallison Avenue',
  'Gamble Street',
  'Gates Avenue',
  'Gaylord Street',
  'Geary Street',
  'George Street',
  'Gibson Street',
  'Gifford Street',
  'Gilbert Street',
  'Gleason Street',
  'Glen Street',
  'Godfrey Street',
  'Goodwin Street',
  'Gordon Street',
  'Grant Street',
  'Green Street',
  'Greenwood Avenue',
  'Gregory Street',
  'Griffin Street',
  'Groton Street',
  'Guernsey Street',
  'Guild Avenue',
  'Hadley Street',
  'Hale Street',
  'Hall Street',
  'Hamilton Avenue',
  'Hammond Street',
  'Hancock Street',
  'Hanover Street',
  'Hardy Street',
  'Harrison Street',
  'Hartley Street',
  'Harvard Street',
  'Hazel Street',
  'Heath Street',
  'Heath Street Ext',
  'Hemenway Street',
  'Hemlock Street',
  'Henderson Street',
  'Henry Street',
  'Hewins Street',
  'High Street',
  'High Street Ext',
  'Hill Street',
  'Hillside Avenue',
  'Hilltop Street',
  'Hiram Street',
  'Hobart Street',
  'Hodge Street',
  'Holcomb Street',
  'Holland Street',
  'Holmes Street',
  'Holt Avenue',
  'Home Street',
  'Hoover Street',
  'Hopkins Street',
  'Howard Street',
  'Howe Street',
  'Hubbard Street',
  'Hubbard Street Ext',
  'Hudson Street',
  'Hughes Street',
  'Huguenot Street',
  'Hull Street',
  'Humphrey Street',
  'Hunter Street',
  'Huntington Avenue',
  'Hurlburt Street',
  'Ingersoll Street',
  'Inman Avenue',
  'Inman Street',
  'Irene Street',
  'Iron Street',
  'Isabel Street',
  'Island Street',
  'Ives Street',
  'Jackson Street',
  'James Street',
  'Jefferson Street',
  'Jenkins Street',
  'Jennison Street',
  'Jerome Street',
  'Jessie Avenue',
  'Johnson Street',
  'Jones Street',
  'Jordan Street',
  'Joseph Street',
  'Judith Street',
  'Juniper Street',
  'Kendall Street',
  'Kent Street',
  'Kerry Avenue',
  'Keyes Road',
  'Kimball Street',
  'King Street',
  'Kingman Street',
  'Kingsbury Street',
  'Kinsman Avenue',
  'Kittredge Road',
  'Knollwood Avenue',
  'Knowlton Street',
  'Knox Avenue',
  'Kossuth Street',
  'Lafayette Street',
  'Lake Avenue',
  'Lake Street',
  'Lakewood Drive',
  'Lamb Street',
  'Lamson Avenue',
  'Lancaster Street',
  'Larkin Avenue',
  'Laurel Street',
  'Lawton Place',
  'Leamy Street',
  'Leary Avenue',
  'LeBlanc Street',
  'Lee Avenue',
  'Leighton Street',
  'Lenox Street',
  'Leonard Street',
  'Leslie Avenue',
  'Lexington Street',
  'Liberty Street',
  'Lincoln Street',
  'Linda Street',
  'Lindell Avenue',
  'Linwood Avenue',
  'Lloyd Street',
  'Locust Street',
  'Lombard Street',
  'Louis Avenue',
  'Lowell Street',
  'Lundberg Avenue',
  'Lundgren Avenue',
  'Luther Street',
  'Lynde Street',
  'Lynwood Avenue',
  'Madison Avenue',
  'Main Street',
  'Malden Street',
  'Manchester Street',
  'Manor Road',
  'Maple Street',
  'Marble Street',
  'Maria Avenue',
  'Marie Avenue',
  'Marie Street',
  'Marion Street',
  'Market Street',
  'Marlboro Street',
  'Marshall Street',
  'Martin Street',
  'Mason Street',
  'Matthews Street',
  'Maxwell Avenue',
  'May Street',
  'Mayfair Street',
  'Mayflower Avenue',
  'Maynard Street',
  'McCaffrey Street',
  'McKay Street',
  'Mechanic Street',
  'Melrose Street',
  'Meriam Avenue',
  'Merriam Avenue',
  'Merrill Street',
  'Merton Street',
  'Metcalf Street',
  'Middle Street',
  'Miles Street',
  'Mill Street',
  'Millbrook Street',
  'Milton Avenue',
  'Monroe Street',
  'Montachusett Avenue',
  'Montgomery Street',
  'Moore Avenue',
  'Moran Avenue',
  'Morgan Street',
  'Morin Street',
  'Morse Avenue',
  'Morton Street',
  'Mount Jefferson Road',
  'Mount Vernon Street',
  'Myrtle Avenue',
  'Myrtle Street',
  'Nadeau Street',
  'Nashua Street',
  'Nashua Street Ext',
  'Nelson Street',
  'Newell Street',
  'Newton Street',
  'Nichols Street',
  'Nickerson Road',
  'Nightingale Street',
  'Norcross Avenue',
  'North Main Street',
  'North Street',
  'Northwest Street',
  'Norway Street',
  'Nye Avenue',
  'Oak Street',
  'Oakland Street',
  'Oaklawn Avenue',
  'Oakwood Lane',
  'Odeon Street',
  'Olde Colonial Drive',
  'Oliver Street',
  'Onyx Street',
  'Orange Street',
  'Orchard Avenue',
  'Orchard Street',
  'Otis Street',
  'Oxford Street',
  'Page Avenue',
  'Palmer Avenue',
  'Parker Street',
  'Parkman Street',
  'Parmenter Street',
  'Parsons Street',
  'Pasquale Avenue',
  'Patton Street',
  'Paul Avenue',
  'Pearl Street',
  'Peckham Street',
  'Pelletier Avenue',
  'Pembroke Street',
  'Penn Avenue',
  'Perkins Street',
  'Perrin Street',
  'Peters Road',
  'Peterson Street',
  'Phillips Street',
  'Pierce Street',
  'Pierpont Street',
  'Pike Avenue',
  'Pine Street',
  'Pinewood Avenue',
  'Pitman Street',
  'Pleasant Street',
  'Pleasant View Avenue',
  'Plum Street',
  'Poland Street',
  'Pond Street',
  'Pope Street',
  'Porter Street',
  'Pratt Street',
  'Prescott Street',
  'Preston Street',
  'Price Street',
  'Princeton Street',
  'Prospect Street',
  'Providence Street',
  'Puffer Street',
  'Pulaski Street',
  'Putnam Street',
  'Quail Run',
  'Quarry Street',
  'Quebec Street',
  'Queen Street',
  'Quimby Street',
  'Quincy Street',
  'Railroad Street',
  'Randall Street',
  'Raymond Street',
  'Reed Street',
  'Revere Street',
  'Rice Avenue',
  'Rich Street',
  'Richards Avenue',
  'Richardson Street',
  'Richmond Avenue',
  'Ridge Avenue',
  'Ridgewood Lane',
  'Rindge Road',
  'River Street',
  'Riverside Road',
  'Robert Street',
  'Rockland Street',
  'Rockwell Street',
  'Roosevelt Street',
  'Ross Street',
  'Round Hill Road',
  'Roy Street',
  'Russell Street',
  'Ryan Street',
  'Sacramento Street',
  'Salem Street',
  'Saliba Avenue',
  'Sanborn Street',
  'Sanderson Street',
  'Sargent Street',
  'Sawyer Street',
  'School Street',
  'Scott Street',
  'Second Street',
  'Sewall Street',
  'Shattuck Street',
  'Sheffield Street',
  'Sheldon Street',
  'Sherman Street',
  'Shirley Street',
  'Short Street',
  'Shrewsbury Street',
  'Silver Street',
  'Simon Street',
  'Sixth Street',
  'Slade Street',
  'South Main Street',
  'South Street',
  'Spaulding Street',
  'Spring Street',
  'Spruce Street',
  'St. James Street',
  'St. John Street',
  'St. Joseph Avenue',
  'St. Paul Street',
  'Stafford Street',
  'Stanley Avenue',
  'Stanton Street',
  'State Street',
  'Sterling Street',
  'Stevens Street',
  'Stone Street',
  'Summer Street',
  'Summit Avenue',
  'Sunnyside Avenue',
  'Superior Avenue',
  'Sutton Street',
  'Talbot Street',
  'Taylor Street',
  'Temple Street',
  'Tenney Street',
  'Thayer Street',
  'Third Street',
  'Thomas Street',
  'Thorndike Street',
  'Thornton Street',
  'Thurston Street',
  'Timpany Boulevard',
  'Tobin Avenue',
  'Tolman Street',
  'Tory Road',
  'Townsend Street',
  'Tracy Street',
  'Tremont Street',
  'Trinity Street',
  'Truax Road',
  'Turner Street',
  'Tyler Street',
  'Union Square',
  'Union Street',
  'Union Street Ext',
  'Unity Avenue',
  'Upland Street',
  'Vale Street',
  'Valley Street',
  'Vernon Street',
  'Victory Street',
  'View Street',
  'Village Street',
  'Vine Street',
  'Vista Avenue',
  'Wachusett Street',
  'Waldo Street',
  'Walker Street',
  'Wallace Street',
  'Walnut Street',
  'Walton Street',
  'Warren Avenue',
  'Washington Street',
  'Water Street',
  'Waverly Street',
  'Waverly Street Ext',
  'Waverly Street Rear',
  'Wayne Street',
  'Webster Street',
  'Wellman Street',
  'Wells Avenue',
  'Wendell Street',
  'West Broadway',
  'West Lynde Street',
  'West Street',
  'West Street Ext',
  'West Street Passway',
  'West Street Rear',
  'Westminster Street',
  'Westwood Drive',
  'Whalon Street',
  'Whipple Street',
  'White Street',
  'Whitman Street',
  'Whittier Street',
  'Wilder Street',
  'Wilkins Road',
  'Willard Street',
  'Williams Street',
  'Willow Street',
  'Wilson Street',
  'Winchendon Road',
  'Winchester Avenue',
  'Winchester Street',
  'Windsor Street',
  'Winter Street',
  'Wood Street',
  'Woodland Avenue',
  'Wright Street',
  'Yale Street',
  'Young Street',
  'Zeda Avenue',
  'Zion Street'
].sort();